# Generated by Django 2.2.2 on 2019-08-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IronStoreTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(max_length=100)),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=100)),
                ('item_quantity', models.IntegerField()),
                ('item_unit_price', models.IntegerField()),
                ('item_total_price', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('damount', models.IntegerField()),
                ('notes', models.TextField()),
                ('cname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('added_at', models.DateTimeField()),
            ],
        ),
    ]
