# Generated by Django 2.2.2 on 2019-08-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iron_store_transactions', '0002_auto_20190825_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ironstoretransactionhistory',
            old_name='receipt_id',
            new_name='receipt',
        ),
        migrations.RenameField(
            model_name='ironstoretransactionitems',
            old_name='receipt_id',
            new_name='receipt',
        ),
    ]
