# Generated by Django 2.2.2 on 2019-08-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_store_transactions', '0003_auto_20190825_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ironstoretransaction',
            name='item_total_price',
        ),
        migrations.AddField(
            model_name='ironstoretransactionitems',
            name='item_total_price',
            field=models.IntegerField(default=0),
        ),
    ]
