# Generated by Django 2.2.2 on 2019-09-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_store_transactions', '0005_remove_ironstoretransactionhistory_item_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ironstoretransaction',
            name='discount',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='ironstoretransaction',
            name='total_amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ironstoretransactionhistory',
            name='damount',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='ironstoretransactionhistory',
            name='paid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ironstoretransactionitems',
            name='item_quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ironstoretransactionitems',
            name='item_total_price',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='ironstoretransactionitems',
            name='item_unit_price',
            field=models.CharField(max_length=100),
        ),
    ]
