# Generated by Django 2.2.2 on 2019-09-07 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iron_store_transactions', '0007_ironstoretransactionhistory_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ironstoretransaction',
            name='advance',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='ironstoretransaction',
            name='first_time_damount',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='ironstoretransaction',
            name='firt_time_paid',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='ironstoretransaction',
            name='today_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
