# Generated by Django 2.2.2 on 2019-08-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bending_press_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ironstoretransactionitems',
            name='lcost',
            field=models.IntegerField(default=0),
        ),
    ]
