# Generated by Django 2.2.2 on 2019-09-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bending_press_transactions', '0002_ironstoretransactionitems_lcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ironstoretransactionhistory',
            name='damount',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='ironstoretransactionhistory',
            name='paid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ironstoretransactionitems',
            name='item_quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ironstoretransactionitems',
            name='item_total_price',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='ironstoretransactionitems',
            name='item_unit_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ironstoretransactionitems',
            name='lcost',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
