# Generated by Django 2.2.2 on 2019-09-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bending_press_transactions', '0004_auto_20190907_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='ironstoretransactionhistory',
            name='advance',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
