# Generated by Django 2.2.2 on 2019-09-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bending_press_transactions', '0005_ironstoretransactionhistory_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ironstoretransaction',
            name='advance',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='ironstoretransaction',
            name='first_time_damount',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='ironstoretransaction',
            name='firt_time_paid',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
