# Generated by Django 2.2.2 on 2019-09-07 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bending_press_transactions', '0006_auto_20190907_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='ironstoretransaction',
            name='today_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
