# Generated by Django 2.2.2 on 2019-09-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bending_press_transactions', '0007_ironstoretransaction_today_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='IronStoreDailyExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.CharField(default=0, max_length=100)),
                ('today_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
