# Generated by Django 2.2.2 on 2019-09-13 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bending_press_transactions', '0008_ironstoredailyexpenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='ironstoretransactionhistory',
            name='today_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
