# Generated by Django 2.2.2 on 2019-08-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
                ('item_subtype', models.CharField(max_length=30)),
                ('item_price', models.IntegerField()),
                ('item_code', models.CharField(max_length=30)),
                ('item_quantity', models.CharField(max_length=30)),
                ('item_description', models.TextField()),
                ('added_at', models.DateTimeField()),
            ],
        ),
    ]
